<?php

return [
    'Pakistan',
    'United States',
    'United Kingdom',
    'Canada',
    'Australia',
    'India',
    'Germany',
    'France',
    'Saudi Arabia',
    'United Arab Emirates',
    'China',
    'Japan',
    'Singapore',
    'Malaysia',
    'South Africa',
    'Brazil',
    'Italy',
    'Spain',
    'Netherlands',
    'Sweden',
    'Norway',
    'Russia',
    'Turkey',
    'Qatar',
    'Kuwait',
    'Philippines',
];
